### ISSUE TITLE
Error when including '@' character in Twitter handle on setup

### ISSUE THREAD

**Issue by humantorch** [sondr3/generator-jekyllized#105]
When creating a new project today, I'd included the `@` symbol when entering my Twitter handle during the project setup. After the setup completed, running `gulp` simply opened a page with `Cannot GET /` displayed and no other content.

The following error showed up in the console output during start-up:
```
jekyll 3.0.1 | Error:  (/Users/scott/Documents/Projects/WebServer/yojek/_config.yml): found character that cannot start any token while scanning for the next token at line 19 column 12
```

The problem is easily resolved by removing the `@` symbol from line 19 in `_config.yml`, but perhaps the Twitter handle-entry step in the initial setup could be a bit clearer (perhaps by already displaying `@` in that step, i.e.: `? Your Twitter handle: @` – make it clear that the user doesn't need to include it).

**Comment by sondr3** [comment]
Ah, yeah, probably a smart idea. I'll push a fix for that when I get home in an hour or so :)
