### ISSUE TITLE
gulp build not working

### ISSUE THREAD

**Issue by wihodges** [sondr3/generator-jekyllized#108]
This very well could be a user issue on my side, but when I run gulp build. The index files for resulting pages and posts inside of the /dist/ directory still have relative path urls.  E.G:

  
  link rel="stylesheet" href="/assets/stylesheets/style.css"
  

Thus when I rsync to server, it's not loading any of the css/js assets.
I've run: gulp rebuild, gulp build --prodcution, gulp jekyll --prod
I noticed too that gulp publish doesn't work, assuming that is from the old branch as I am using the latest beta branch.

**Comment by sondr3** [comment]
The URLs should be relative, I haven't had any issues with it. However your issue does sound a bit strange. I'll take a look when I'm done at work.

**Comment by wihodges** [comment]
Yea user mistake. So I thought that by specifying the domain and subdirectory in the config.yml would take care of URL, but apparently deploying into subdirectory causes the issue with asset URL paths. 
So the issue was trying to deploy(rsync) to subdirectory.

**Comment by sondr3** [comment]
Ah, yeah, that it does. I should probably mention that in the FAQ. Glad you figured it out :)
