### ISSUE TITLE
Where does the 'touch' folder come from?

### ISSUE THREAD

**Issue by liquidvisual** [sondr3/generator-jekyllized#109]
When I run a `gulp build`, I've noticed in **dist/assets/images/** there's always a folder called **/touch** - regardless of whether I have that folder or file in my source. I can't seem to stop it generating. Any ideas?

**Comment by sondr3** [comment]
Really? If you look in `assets/images` there should be a `touch` folder with a image in it. It's just my way of putting favicons and such for all the different browsers and so on in a folder so I don't litter the `images` folder with favicons.

**Comment by liquidvisual** [comment]
It's strange, when I delete that folder with the image - it still generates the (empty) folder on build. I can't find any code in the Gulpfile that points to it.

**Comment by sondr3** [comment]
Strange, which version of the generator are you running?

**Comment by liquidvisual** [comment]
Latest one, I did a fresh `yo jekylized` a few hours ago.

**Comment by sondr3** [comment]
So you mean the beta then or the latest default version?

**Comment by liquidvisual** [comment]
I'm not 100% sure, but I installed via the main instructions - so I'm pretty sure it's the beta:

`npm install generator-jekyllized@1.0.0-beta.6 -g`

**Comment by sondr3** [comment]
Yeah, that's the beta. :) If you haven't deleted the `touch` folder from your `assets` folder, try that and run `gulp clean:assets` and `gulp images`. It shouldn't create the `touch` folder then, it might just be lingering about in the temporary folder.

**Comment by liquidvisual** [comment]
I gave it a go, but the touch folder still remained. I did manage to fix it by going into the .tmp folder and deleting it directly - seemed to do the trick. Thanks for getting back so quick :)

**Comment by sondr3** [comment]
Running `gulp clean:assets` should clean out the `.tmp` folder though, so that's a bug. I'll take a look at it. And no worries, hope it works fine :)

**Comment by liquidvisual** [comment]
Oh, one more quick question while I have you - on the index.html - what does `regenerate: true` do? I can't seem to find any docs online explaining it in detail.

**Comment by sondr3** [comment]
It's because of the incremental regeneration that Jekyll 3.0 introduced, without it having `regenerate: true` the posts on the frontpage won't update whenever you edit a post and will only display the markdown without being converted to HTML. You can try for yourself and see, but I do suggest you leave it in. Otherwise you have to re-build your site whenever you're done editing posts.

**Comment by liquidvisual** [comment]
Excellent, thanks for the tip! And kudos for this fantastic generator. I'll be using it for all my future projects now. :)

**Comment by sondr3** [comment]
No problem, and no worries. Do let me know if you run into any errors or problems along the way :)
