### ISSUE TITLE
I need help to deploy my project to gh-pages

### ISSUE THREAD

**Issue by emilianos** [sondr3/generator-jekyllized#110]
Hello, I'm new to using Yeoman generators, Gulp and all that. I'm also more a designer than developer. I can find my way around the command line though..

What I'm having problems with, is understanding the process of pushing my project to gh-pages, so it will be visible in my repo, and also be available through "username.github.io".
Only using the command `gulp deploy ` should do everything right?

>If you chose to upload to Github Pages there's no configuration besides starting a git repo in your folder,
`git init` ?
>setting an origin remote repo
`git remote add origin https://github.com/username/username.github.io.git` ?
>and run gulp deploy. Your site will be automatically pushed to Github. See the FAQ for configuring personal repos vs project repos.

I have manually pushed the code to my repo here:
https://github.com/emilianos/emilianos.github.io

I've read these guides:
http://jekyllrb.com/docs/github-pages/
https://help.github.com/articles/using-jekyll-with-pages/
https://github.com/sondr3/generator-jekyllized#gulp-deploy
https://github.com/sondr3/generator-jekyllized#frequently-asked-questions

https://github.com/tschaub/gh-pages
https://github.com/shinnn/gulp-gh-pages

Any help mush appreciated!
Thank you!!

**Comment by sondr3** [comment]
You've edited your gulpfile wrong already, you're not supposed to push to the master branch, revert that change and make it as it was. It needs to push to the `gh-pages` branch, which it does by default when you run `gulp deploy`.

And yes, all you need to do is init a repo, set a remote origin on Github and run `gulp deploy`.

**Comment by sondr3** [comment]
Obviously you should run the generator with either `gulp build --prod` or `gulp --prod`, and then deploy it but otherwise what I've said is correct.

**Comment by emilianos** [comment]
Thank you for your answer!

Here's what I did:
- first updated `generator-jekyllized@1.0.0-beta.7` and `gulp-gh-pages@0.5.4`
- generated a brand new project
- had these errors:

>Configuration file: /Users/emiliano/Documents/_dev/jekyllized/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-archives or one of its dependencies installed...

- Since I did have those same errors the first time using Jekyllized I fixed them the same way:
```
sudo bundle clean --force
bundle update
```
- now I have a new problem in the new project:
```
gulp build

[00:16:43] Requiring external module babel-core/register

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: Task never defined: gulp clean:images
    at getFunction (/Users/emiliano/Documents/_dev/jekyllized-3/node_modules/undertaker/lib/helpers/normalizeArgs.js:14:5)
    at arrayMap (/Users/emiliano/Documents/_dev/jekyllized-3/node_modules/lodash/index.js:1406:25)
    at Function.map (/Users/emiliano/Documents/_dev/jekyllized-3/node_modules/lodash/index.js:6710:14)
    at normalizeArgs (/Users/emiliano/Documents/_dev/jekyllized-3/node_modules/undertaker/lib/helpers/normalizeArgs.js:18:12)
    at Gulp.series (/Users/emiliano/Documents/_dev/jekyllized-3/node_modules/undertaker/lib/series.js:13:14)
    at Object.<anonymous> (gulpfile.babel.js:263:27)
    at Module._compile (module.js:397:26)
    at loader (/Users/emiliano/Documents/_dev/jekyllized-3/node_modules/babel-register/lib/node.js:134:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/emiliano/Documents/_dev/jekyllized-3/node_modules/babel-register/lib/node.js:144:7)
    at Module.load (module.js:343:32)
```

- And if I go to the old project and do a `gulp build` gives me 2 warnings:
```
WARN: Unresolved specs during Gem::Specification.reset:
      rb-inotify (>= 0.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/emiliano/Documents/_dev/jekyllized-2/_config.yml
            Source: src
       Destination: dist
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 2.689 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```
- and then i do `gulp deploy` and I get:
```
[00:34:05] Error in plugin 'gulp-ch-pages'
Message:
    Command failed: /bin/sh -c git rev-list --pretty=raw --max-count=1 
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all

Details:
    killed: false
    code: 129
    signal: null
    cmd: /bin/sh -c git rev-list --pretty=raw --max-count=1 
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by sondr3** [comment]
Strange. I'll take a closer look at it as soon as I can. Looks like the uploader doesn't work anymore. And I'll look into the other issues as well.

**Comment by sondr3** [comment]
The first and third one are most likely an error with your local environment and such. What version of Ruby are you using and how do you manage your gems? Because it's an error that you get when you have older versions of gems installed that take precedent over the newer ones.

The second was purely my fault, I messed up the syntax in the gulpfile for one of the tasks, I'll push a fix ASAP. As for the last one with Github pages, I have no idea. Are you running an outdated version of Git maybe? I just created a new site and pushed it to Github and ran `gulp deploy` and it worked just fine: https://github.com/sondr3/testjekyll.

**Comment by emilianos** [comment]
Thank you again for looking into it. I probably have problems with versions yes, I tried to update everything I could but I'm not sure if there are maybe dependencies that are also outdated.

These are my current versions:
```
jekyll 3.0.2
yo 1.6.0
git version 2.5.4 (Apple Git-61)
nam 3.7.1
gem 2.5.2
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
gulp -v
Requiring external module babel-core/register
CLI version 0.4.0
Local version 4.0.0-alpha.2
```

I have installed the gems with the `gem install` command, and most of the tools using `npm`

**Comment by emilianos** [comment]
Almost there I think..
I upgraded to the latest version of Jekyllized beta.8 (thank you!)
and started a new project from scratch.

Now when I do gulp deploy it asks me for a username and password (which is the first time to happen!).
Then throws back this error:

```
gulp deploy
[16:32:27] Requiring external module babel-core/register
[16:32:29] Using gulpfile ~/Documents/_dev/jekyllized-3test/gulpfile.babel.js
[16:32:29] Starting 'deploy'...
Username for 'https://github.com': emilianos
Password for 'https://emilianos@github.com': 
[16:32:57] 'deploy' errored after 29 s
[16:32:57] Error in plugin 'gulp-ch-pages'
Message:
    Command failed: /bin/sh -c git clone https://github.com/username/username.github.io.git .publish
Cloning into '.publish'...
remote: Repository not found.
fatal: repository 'https://github.com/username/username.github.io.git/' not found

Details:
    killed: false
    code: 128
    signal: null
    cmd: /bin/sh -c git clone https://github.com/username/username.github.io.git .publish
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

looks like its not getting my github username? is there any other config needed?

**Comment by sondr3** [comment]
It looks as if you haven't authenticated yourself with Github via SSH. You might want to look [here](https://help.github.com/articles/generating-an-ssh-key/). Also, did you just copy and paste the username? Because it looks like it's trying to upload to `username` instead of `emilianos`. It might be because of lacking authentication.

I might just look into using a different plugin than the `gulp-gh-pages` because it looks like a bunch of people are having issues with it. I'll take a look tomorrow after work.

**Comment by emilianos** [comment]
Ok, just completed all the steps to autenthicate via SSH, ~~but still no luck~~ and now its working!
I realised that I did in fact not changed `username` with `emilianos` :unamused:

Now I have to find out how to make that show up in http://username.github.io

Thank you for your help, much appreciated!

**Comment by emilianos** [comment]
Just added this to the gulpfile and it works like charm!! amazing!!

```
gulp.task('deploy', () => {
  return gulp.src('dist/**/*')
    .pipe($.ghPages({
      branch: "master"
    }));
});
```

**Comment by sondr3** [comment]
Fantastic. Glad to hear it. Let me know if you need anything else :)
