### ISSUE TITLE
in development, css changes don't take effect without !important

### ISSUE THREAD

**Issue by ryanaponte** [sondr3/generator-jekyllized#111]
Huge thanks for this project!

I'm on the beta branch and have run into an issue where css changes don't get applied. If I add `!important` to a style, it gets applied, and then I can remove `!important` and it persists.

This is the case whether I'm running with `--prod` or without. Any suggestions?

**Comment by sondr3** [comment]
Have you verified that the CSS file that's generated changes when you remove `important`? Otherwise it might be that it's applied in your browser but not cleared when it changes.

**Comment by chbachman** [comment]
I'm having the same problem. The CSS file does change when you remove !important. The browser doesn't seem to recgonize a change until you add !important to the style changing.

**Comment by sondr3** [comment]
Strange, I'll have a look and see what I can figure out. It'll probably take some time as I'm away from my computer for the weekend.

**Comment by chbachman** [comment]
Thanks for taking a look at it. It is pretty strange.

**Comment by sondr3** [comment]
You wouldn't be able to push an example repo to Github in the meantime though?

**Comment by chbachman** [comment]
I can. It works with the default generated website, though.

**Comment by chbachman** [comment]
I added the affected website here: https://github.com/chbachman/Garden

Its the default generation.

**Comment by sondr3** [comment]
Thanks, any quick steps to reproduce so I don't stumble around? Just to make sure I fully understand how it works.

**Comment by chbachman** [comment]
1. Run the livereload on the website. 
2. Change the css, the page doesn't recognize any of the changes.
3. Add !important to the changed line, the webpage will recognize the changes, and update.

**Comment by sondr3** [comment]
Very strange, thanks, I'll take a look.

**Comment by sondr3** [comment]
Fixed in #117 :smile:
