### ISSUE TITLE
Suggestion: consider using Usemin blocks for JavaScripts?

### ISSUE THREAD

**Issue by liquidvisual** [sondr3/generator-jekyllized#112]
Hi sondr3! I've just about finished porting over my old generator-jekyllrb project over into jekyllized - but have hit a bit of a snag, which may be a deal breaker going forward :(

I've noticed assets, particularly the JavaScripts need to be declared inside the actual Gulpfile - which feels really cumbersome. A much better method (IMO) I've been using, is through [usemin](https://www.npmjs.com/package/gulp-usemin) blocks which allows you to declare scripts inside the HTML. Usemin will then wrap it all up without you needing to jump back and forth between the source files and Gulpfile. 

Example in **default.html**:

```
<!-- build:js /assets/javascripts/optimized.js -->
    <script src="/assets/javascripts/foo.js"></script>
    <script src="/assets/javascripts/bar.js"></script>
 <!-- endbuild -->
```

Would love to know your thoughts on this. My skills in this area aren't too advanced, so I'm not really sure about how to implement such a change. Cheers,

**Comment by sondr3** [comment]
I used to do this but it was extremely cumbersome and annoying, mostly because of how you had to structure the gulp tasks to do what it does now. I'd love it if it somehow worked better now however, but I haven't looked in a wee while.

**Comment by liquidvisual** [comment]
Understood. I'll keep looking. Cheers,

**Comment by sondr3** [comment]
I'll let you know if I figure something out, I know it's not the most elegant solution right now, but it's the best one I've figured out that lets me keep my sanity :smiley:
