### ISSUE TITLE
gulp-sass ignoring some changes

### ISSUE THREAD

**Issue by andgatjens** [sondr3/generator-jekyllized#118]
Hi,

First of all, thanks for the great generator.
I'm having a really weird issue. It seems that gulp-sass is ignoring some of my changes if they are almost the same. Let me explain it and show you my task:

```javascript
gulp.task('styles', () =>
  gulp.src('src/assets/scss/main.scss')
    .pipe($.if(!argv.prod, $.sourcemaps.init()))
    .pipe($.sass({
      precision: 10,
      includePaths: ['.', 'bower_components/bootstrap-sass/assets/stylesheets/']
    }).on('error', $.sass.logError))
    .pipe($.postcss([
      autoprefixer({browsers: 'last 1 version'})
    ]))
    .pipe($.size({
      title: 'styles',
      showFiles: true
    }))
    .pipe($.if(argv.prod, $.rename({suffix: '.min'})))
    .pipe($.if(argv.prod, $.if('*.css', $.cssnano())))
    .pipe($.if(argv.prod, $.size({
      title: 'minified styles',
      showFiles: true
    })))
    .pipe($.if(argv.prod, $.rev()))
    .pipe($.if(!argv.prod, $.sourcemaps.write()))
    .pipe($.if(argv.prod, gulp.dest('.tmp/assets/stylesheets')))
    .pipe($.if(argv.prod, $.if('*.css', $.gzip({append: true}))))
    .pipe($.if(argv.prod, $.size({
      title: 'gzipped styles',
      gzip: true,
      showFiles: true
    })))
    .pipe(gulp.dest('.tmp/assets/stylesheets'))
    .pipe($.if(!argv.prod, browserSync.stream()))
);
```
Inside ''src/assets/scss/main.scss', I include all the partials scss that I need on my project (ex: @import "modules/nav")

So, let say I made a change on the '_nav.scss' file, and add a font size property like this: 'font-size: 20px' on a list item of the nav. It properly update the builded css, and update the font size, BUT, I then change the same font-size for let says '15px', it will run the task, but will not update properly the builded css. Only if I made a bigger change, like '115px' or something like that.

Here is a video showing the issue: http://screencast.com/t/QHXIbLCGqnM

I already tried it on my local with just the gulp-sass library and it worked fine. I guess it is something else on the gulpfile.

Thanks,
Andres

**Comment by sondr3** [comment]
Hey, yes, this was an issue that existed in the previous version of the generator. You need to change the last line of that gulp task to be `.pipe($.if(!argv.prod, browserSync.stream({match: '**/*.css'})))`. :)

**Comment by andgatjens** [comment]
Hi @sondr3, thanks for the quick reply. Sadly, this does not fix the issue, I'm still having the same issue that I showed on the video.

**Comment by sondr3** [comment]
That's really strange, never had any issues with Sass directly, only the injection. Can you upload a example repo I can try and see for myself?

**Comment by andgatjens** [comment]
@sondr3 Sure! Here you go: https://github.com/andgatjens/test-jekyllized
I tried changing the ['font-size' of the '.post-title' class on 'layout.scss', line '206'.](https://github.com/andgatjens/test-jekyllized/blob/master/src/assets/scss/layout.scss#L206)
It didn't change the value if the change is small, like font-size: 40px.

Thanks for your time. :)

**Comment by sondr3** [comment]
Are you sure it's not changing? Because most likely what happened was what happened with the previous version, it would update the CSS but not inject it into the browser. Did you check the generated CSS if the changes were applied (as in opened the file in your editor to see if it actually changed and that it wasn't simply not being injected)? In either case, I've downloaded your repo and tried it out and it changes the size no matter what I set it to.

Try downloading updating the gulpfile to the latest one and see again. Reinstall `generator-jekyllized` again and run `yo jekyllized:gulp`, it'll update to the latest version of the gulpfile. Just make a backup of the older ones if you made any changes and then try again :smiley:

**Comment by sondr3** [comment]
Also, when you were doing the changes, when you looked in the terminal, did it update like this:

```sh
[BS] 2 files changed (style.css.map, style.css)
[01:49:53] Finished 'styles' after 67 ms
[01:49:53] Finished '<series>' after 67 ms
[01:49:58] Starting '<series>'...
[01:49:58] Starting 'styles'...
[01:49:58] styles style.css 8.35 kB
[BS] 2 files changed (style.css.map, style.css)
[01:49:58] Finished 'styles' after 63 ms
[01:49:58] Finished '<series>' after 64 ms
[01:50:01] Starting '<series>'...
[01:50:01] Starting 'styles'...
[01:50:01] styles style.css 8.35 kB
[BS] 2 files changed (style.css.map, style.css)
[01:50:01] Finished 'styles' after 70 ms
[01:50:01] Finished '<series>' after 71 ms
[01:50:13] Starting '<series>'...
[01:50:13] Starting 'styles'...
[01:50:13] styles style.css 8.35 kB
[BS] 2 files changed (style.css.map, style.css)
[01:50:13] Finished 'styles' after 103 ms
[01:50:13] Finished '<series>' after 103 ms
```

every time you saved?

**Comment by sondr3** [comment]
I just noticed that running `yo jekyllized:gulp` will ignore any uploading choices you've done, just a quick FYI. I'm trying to find a better way to do this.

**Comment by sondr3** [comment]
And I've fixed that now, you can run `yo jekyllized:gulp [--rsync|amazon|pages]` and update it.

**Comment by andgatjens** [comment]
I updated on my local the new version of the generator, and with that it worked fine, so I guess I will have to see what could be possible affecting, and change that on my project, since my gulpfile already has a lot of other stuff 😄 . I really really appreciate your time, thanks for your help!

**Comment by sondr3** [comment]
Awesome, happy to hear that :)
