### ISSUE TITLE
Gulp --prod not linking to asses correctly

### ISSUE THREAD

**Issue by mckeever02** [sondr3/generator-jekyllized#119]
Hi Sondr3,

Seems I'm running into another strange issue. When I use `gulp --prod` or `gulp build --prod` the .css and .js files are not linked to correctly in the dist folder. For instance in my src/head.html I'll have something like:
```
  <!-- CSS -->
  <!-- inject:css -->
  <link rel="stylesheet" href="assets/stylesheets/style-152365af71.min.css">
  <!-- endinject -->
```

Which is correct, but in one of my static files in dist, it'll have:

`<link rel=stylesheet href=assets/stylesheets/style.css>`

Which is obviously incorrect. Any ideas why the links to these assets aren't being generated correctly in dist?

Thanks for your time

**Comment by sondr3** [comment]
Hmm, not really. Is this in one of the pages? Or in a post?

**Comment by mckeever02** [comment]
Its all posts and pages. For whatever reason its not grabbing the correct name from src/head.html

**Comment by sondr3** [comment]
You haven't changed anything in the gulpfile or in the config files?

**Comment by sondr3** [comment]
Because this is something that'll happen if you have incremental regeneration turned on in Jekyll.

**Comment by mckeever02** [comment]
I only made the one change in config to add a root slash, but that wouldn't be the issue. Im not sure what incremental regeneration is or how to enable it so don't think it'd be that either. 

Here's the repository if you want to have a look: https://github.com/mckeever02/jekyllized-test 
Might see something I don't

**Comment by sondr3** [comment]
I figured out what was happening, it had something to do with LSI. If you go into your `_config.build.yml` file and comment out `lsi: true` it should start working again.
