### ISSUE TITLE
yargs error when running the beta

### ISSUE THREAD

**Issue by nsbingham** [sondr3/generator-jekyllized#121]
After running `yo jekyllized` I'm getting the error below. All dependencies versions match what's outlined in the README. Nothing is generated. Installed with `npm install generator-jekyllized@next -g`.

```Error: Cannot find module 'yargs'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/nate/npm/lib/node_modules/generator-jekyllized/generators/gulp/index.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)```

**Comment by nsbingham** [comment]
Ah, looks like the dependency might have been left out of the package.json.

**Comment by sondr3** [comment]
That's so strange, I added it to the dev dependencies and it all worked locally. I'm at work right now so I'll fix it when I get home. I probably just have to move it the regular dependencies and then it'll work. I hope. Thanks for letting me know :)

**Comment by sondr3** [comment]
I've tried to reproduce this on my own computer but just can't seem to get it to not work, haha. I've reinstalled, `npm link` twice, removed and everything, but locally on my end it works just fine. What version of NPM and Node are you using?

**Comment by sondr3** [comment]
Also, would love to hear from you @CGTS :)

**Comment by CGTS** [comment]
I'm on windows running:
```
Node 4.4.3
NPM  3.8.6
```
I tried moving "yargs" to regular dependencies in the package.json file and error switched to

```
npm ERR! EBUSY: resource busy or locked, rename
C:\Users\user\AppData\Roaming\npm\node_modules\generator-jekyllized' ->
C:\Users\user\AppData\Roaming\npm\node_modules\.generator-jekyllized.DELETE'
```
I read a lot of recommendations about rebooting and cleaning my cache but none of them fix the error.

**Comment by sondr3** [comment]
I've figured out what broke it, I'll deploy a fix ASAP.

**Comment by mdrmike** [comment]
Great, was hoping to give a demo of it tonight at [WAPRO Meetup](http://j.mp/WAPRO-1604)

And not to jump on the _same here_ band wagon, but thought I'd share a bit about my environment in case it matters.   (doesn't sound like it does, but might be worth sharing)

  -  Ubuntu 15.10 desktop 
  - ... I just rebuilt my environment today based on this [stackoverflow best(?) practice](http://stackoverflow.com/questions/16151018/npm-throws-error-without-sudo/24404451#24404451)
    1. Uninstalled Nodejs including [manual deletion suggested here, only also used `sudo`](http://stackoverflow.com/a/19357869)
    1. Manual install of [nvm](https://github.com/creationix/nvm)
    1. `nvm install 5.6`  (also tried `nvm install stable`)
    1. `npm install -g yo`
    1.  `mkdir myrpoject && cd myproject`
    1. `npm install gulpjs/gulp-cli#4.0 -g`
    1. `npm install generator-jekyllized@next -g`
    1. `yo jekyllized`
  1. manually try `npm install yargs` and fails with different `yargs` error
    1. discovered `NODE_PATH` not set, nor in instructions... hmm?  added: `export NODE_PATH="`which node`:`npm root -g`" to `~/.bash_aliases` && `~/.zshrc` (others might add it to `~/.basahrc` or `~/.profile`)
    1. still dead.  hoping release fixes  :)

**Comment by sondr3** [comment]
If you want to revert to a working version you can install it as `npm install -g generator-jekyllized@1.0.0-beta.14`, I've figured out what the error was however for some reason `browser-sync` isn't working for me at all anymore, so I'm trying to figure that out before pushing a fix.

**Comment by sondr3** [comment]
Not really sure about the environment though, I'm on OS X and just install the latest version of Node via Homebrew, so I'm sorry I can't be of any help there sadly. However, if the error you're getting is the same as the one in the OP reverting to an earlier version will work :)

**Comment by nsbingham** [comment]
I'm running:
* OSX 10.11.4 (15E65)
* Node v4.4.3
* NPM 2.15.1
* yo 1.7.0

FWIW I just ran `npm install yargs` in the directory the generator-jekyllized is installed in and that fixed the issue I was having, which led me to my early comment about it possibly being missing from the package.json. After that it's been smooth sailing. BrowserSync is even working for me.

**Comment by sondr3** [comment]
Yeah, once you add it as a dependency it works. It's just something stupid going on with my computer.

**Comment by sondr3** [comment]
Okay, I've pushed a new version to NPM, could you guys try it again and see if it works this time?

**Comment by CGTS** [comment]
I pulled down the updated project and ran "yo jekyllized" and everything was able to load. Unfortunately when I tried to run `gulp` I got the following error:

```
Requiring external module babel-core/register
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'C:\Users\user\.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at save (C:\_lab\onv\node_modules\babel-register\lib\cache.js:48:19)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```
I don't know if this is due to something in the project or just on my end. I'll continue to look into it. 

Thanks for the quick turnaround on the `yargs` issue

**Comment by sondr3** [comment]
That error looks like a file system error, it's saying you're not allowed to to open a specific file. Not sure why though.

**Comment by CGTS** [comment]
We have all kinds of restrictions and admin rights on our machines here at work. I have no doubt it has something to do with that. Thanks again for your help.
