### ISSUE TITLE
Gulp build error with Jekyll-feed "feed_meta" include.

### ISSUE THREAD

**Issue by timkinnane** [sondr3/generator-jekyllized#123]
Hi, just had the following error running gulp (first time, on beta branch):

```
[18:59:34] Starting 'jekyll'...
Configuration file: PROJECT_PATH/_config.yml
            Source: src
       Destination: dist
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: both URI are relative in _includes/head.html, included in _layouts/default.html
jekyll 3.1.2 | Error:  both URI are relative
```

I looked for the issue in _inlcudes/head.html and got it to go away and build properly only when I removed the `feed_meta` (jekyll-feed RSS generator) include.

Any ideas?

**Comment by sondr3** [comment]
Not really, that sounds like a weird error. Could you try to clean out your gems and install them again?

**Comment by MichaelKaeser** [comment]
I do have the same issue, till now only removing `{% feed_meta %}` in `_includes/head.hml`does solve it...also reinstalling the jekyll-feed gem doesn't help. @timkinnane Did you found a solution?

**Comment by sondr3** [comment]
That's really strange, I've forced cleaned my gems and reinstalled them and it works every time for me. Can you post your Ruby version, Jekyll version and the gems used (`bundle list`)?

**Comment by MichaelKaeser** [comment]
```
ruby 2.3.0p0
jekyll 3.1.2

*** LOCAL GEMS ***

addressable (2.4.0)
bigdecimal (default: 1.2.8)
chunky_png (1.3.5)
colorator (0.1)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
did_you_mean (1.0.0)
faraday (0.9.2)
ffi (1.9.10)
io-console (default: 0.4.5)
jekyll (3.1.2)
jekyll-archives (2.1.0)
jekyll-feed (0.5.0)
jekyll-gist (1.4.0)
jekyll-paginate (1.1.0)
jekyll-sass-converter (1.4.0)
jekyll-seo-tag (1.3.3)
jekyll-sitemap (0.10.0)
jekyll-watch (1.3.1)
json (default: 1.8.3)
kramdown (1.10.0)
liquid (3.0.6)
listen (3.0.6)
mercenary (0.3.6)
minitest (5.8.3)
multi_json (1.11.2)
multipart-post (2.0.0)
net-telnet (0.1.1)
octokit (4.3.0)
power_assert (0.2.6)
psych (default: 2.0.17)
rake (10.4.2)
rb-fsevent (0.9.7)
rb-inotify (0.9.7)
rdoc (default: 4.2.1)
redcarpet (3.3.4)
rouge (1.10.1)
rubygems-update (2.6.3)
safe_yaml (1.0.4)
sass (3.4.22)
sawyer (0.7.0)
test-unit (3.1.5)
```

**Comment by sondr3** [comment]
Yep, something happened between `jekyll-feed` 0.4.0 and 0.5.0, I'll take a look.

**Comment by MichaelKaeser** [comment]
Ok, meanwhile I installed version 0.4.0. That's working out so far, thanks for the hint!

**Comment by sondr3** [comment]
I figured it out, not really sure what gives, but the `url` has to include `http://`, so if it was `www.test.com` it now has to be `http://www.test.com`, I'll update the generator when I figure out a good solution.

**Comment by timkinnane** [comment]
Cheers for following up guys, seems you figure it out while I was sleeping. Thanks 👍

**Comment by sondr3** [comment]
I just pushed a fix for this to NPM :smiley:
