### ISSUE TITLE
Generator Error 'output is not defined'

### ISSUE THREAD

**Issue by Roang-zero1** [sondr3/generator-jekyllized#124]
Hi,

in the latest npm package for beta 18 there is a filter in the generators/app/index.js file.
In this filter the variable output is missing its var declaration
`output = 'http://' + input;`

Due to this the generation breaks. Simply adding the var keyword fixes it.
`var output = 'http://' + input;`

**Comment by sondr3** [comment]
Crap, I wasn't supposed to add that to the latest release but it seems I added it by accident. I'll fix it when I get home from vacation.

**Comment by sondr3** [comment]
Crap, I wasn't supposed to add that to the latest release but it seems I added it by accident. I'll fix it when I get home from vacation.

**Comment by mckeever02** [comment]
@Roang-zero1 Could you tell me where exactly to find the index.js file to add this to? I'm getting the same error when I try to run the generator

Thanks

**Comment by Roang-zero1** [comment]
@mckeever02 The file can be found in `<node_modules_path>/generator-jekyllized/generators/app/index.js` where `node_modules_path` is you node modules installation path.

I've created a gist with my patch: [index.js.patch](https://gist.github.com/Roang-zero1/a7f36b670035afe5c0f4f17bb37bee03)
