### ISSUE TITLE
Update jekyll-archives configuration for tags permalink

### ISSUE THREAD

**Issue by ferrarimarco** [sondr3/generator-jekyllized#126]
The [permalink directive](https://github.com/sondr3/generator-jekyllized/blob/beta/generators/jekyll/templates/config.yml#L70) for tags in jekyll-archives module configuration is wrong.

Currently it's:
`tags: '/tag/:name/'`

Should be:
`tag: '/tag/:name/'`

Source: https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md#permalinks

Thanks for this generator

**Comment by sondr3** [comment]
I'm probably going to remove it in the future regardless as it's not really being updated much and I want this to be as close as possible to a barebones default Jekyll site. But thanks for letting me know however! :smiley:

**Comment by ferrarimarco** [comment]
What's not being updated? This generator or the jekyll-archives module?

Thanks

**Comment by sondr3** [comment]
The jekyll-archives gem, I'm always updating this generator. :)
