### ISSUE TITLE
Use a temporary directory for Jekyll data to avoid modifications to src contents when injecting

### ISSUE THREAD

**Issue by ferrarimarco** [sondr3/generator-jekyllized#127]
Currently the inject:head and inject:footer tasks work directly with `src/_includes/head.html` and with `src/_layouts/default.html`.

This leads to source code modifications after each build.

A solution to this issue (that I implemented in [my gulp file](https://github.com/ferrarimarco/personal-website/blob/a27c3a473f45f38b3b233c4ddd9962244c775097/_config.yml)) is:

1. Serve assets from '.tmp/serve' instead of '.tmp'
2. Copy src contents (minus assets) to '.tmp/jekyll-build'
3. Run Jekyll pointing '.tmp/jekyll-build' in _config.yml
4. Update paths for other Gulp tasks accordingly

EDIT: maybe jekyll-build should me changed to something like src-jekyll-preprocessed to further clarify.

**Comment by sondr3** [comment]
Hmm, that's true and something I hadn't thought of either, but it's not something that I have a big problem with. I'll take a look at it though and see if I can figure out something better :smiley:

**Comment by ferrarimarco** [comment]
Please look at [my updated gulp file](https://github.com/ferrarimarco/personal-website/blob/7213741e4dfdda2b77bafd59357b27a7525c857d/gulpfile.babel.js). A solution is already in place.

Currently I use three directories in .tmp:
1. jekyll-preprocessed-src: everything to process with Jekyll, after injections
2. jekyll-built: jekyll results
3. assets-built: preprocessed assets (js, CSS, images, favicon)

**Comment by sondr3** [comment]
Sweet, feel free to send PRs for these if you want to. Otherwise I'll tackle then in a few weeks.

**Comment by ferrarimarco** [comment]
The build is already broken, so it's difficult to write integration tests.

**Comment by sondr3** [comment]
Yeah, something is broken in one of the testing packages, not really sure what gives, I'll take a look.
