### ISSUE TITLE
Typo for gulp-gh-pages in uploading.js gulp task

### ISSUE THREAD

**Issue by mitchrenton** [sondr3/generator-jekyllized#139]
In uploading.js (../gulp/tasks/uploading.js) on line 3...

`const ghpages = require('gulp-ghpages');`

Notice there is no hyphen between 'gh' and 'pages' - this prevents the 'gulp' task from running.

Adding the hyphon fixes this, thought I'd let you know 👍

**Comment by sondr3** [comment]
Thanks! I'll push a fix later tonight.

**Comment by sondr3** [comment]
And done, I've pushed a fix to the base generator, thanks! 😃
