### ISSUE TITLE
archive templates still in package

### ISSUE THREAD

**Issue by placenamehere** [sondr3/generator-jekyllized#140]
It looks like the archive templates (`_layouts/*_archive.html`) still exist in the repo / generator output even though you had deciding to remove the `jekyll-archives` dependencies  and related config at some point.

This inclusion cause me some confusion and lost time with a new project as I was attempting to chase down why some of the included templates weren't compiled. 

Unless there's a good reason for them to exist, I'd suggest for clarity and benefit of future users of this generator the templates be removed so that the code is consistent with the supported features.

**Comment by sondr3** [comment]
Crap, I thought I remembered to remove those when upgrading the generator, I'll look into it as soon as I have time. Might be a bit over a week since I'm going on a vacation in the mean time 😃
