### ISSUE TITLE
dot files supported by jekyll not supported in generator config

### ISSUE THREAD

**Issue by placenamehere** [sondr3/generator-jekyllized#141]
While the jekyll default config has support for some dot files (such as `.htaccess`) they were not being moved from `src` to `tmp` on the copy steps that precede the jekyll processing, so any build or deploy I was doing was not inclusive of these files.

Locally, I fixed this by adding `,{dot: true}` to the appropriate `gulp.src()` calls in my `gulpfile.js`.

**Comment by placenamehere** [comment]
digging into how `gulpfile.js` is being generated it looks like the fix would be needed to both the move to tmp task in generator-jekyllized as well as the deploy task which is inherited from generator-statisk:

https://github.com/sondr3/generator-jekyllized/blob/master/generators/jekyll/templates/build.js#L10
https://github.com/sondr3/generator-statisk/blob/master/generators/gulp/templates/tasks/uploading.js#L50

**Comment by sondr3** [comment]
Thanks! Didn't think about this as I don't use Apache or anything requiring dotfiles, I'll fix this one as well as soon as I can!

**Comment by sondr3** [comment]
Okay, so I'm fixing this one right now but do we need to add support for dotfiles to both GitHub Pages and Amazon AWS? As far as I know neither of those have any files that are dotfiles, whereas for rsync you might need them for Apache and such. Any feedback?

**Comment by placenamehere** [comment]
I tend to always lean towards predictability -- if part of the process copies files into a staging location (`dist`) I'd expect the second half of the process to always be configured to work against all those files.

Yes, probably not needed for github or aws (that I know of) but if a developer using this has one in their project it should probably be deployed (and then ignored by the 'server')

I'd say that because this choice/config is buried in a dependent package I'd also lean towards being more accepting in that package by default.

**Comment by sondr3** [comment]
Alright, sounds good to me, I'll update them and push a new version pretty soon.

**Comment by sondr3** [comment]
And done! I accidentally tagged the wrong commit so I'll have to close it myself, I'll create a new release of both generators ASAP.

**Comment by sackwort** [comment]
My .htaccess file is not being copied into 'dist' when I run 'gulp build'. I'm using latest RC. I've also tried adding as an include in _config.

**Comment by sondr3** [comment]
Crap, I can see why, when updating your app it only looks at what has changed from `generator-statisk` and not from this generator, I'll fix this as soon as I can, but it might take a few days, in the mean time the second comment here includes a fix.

**Comment by sackwort** [comment]
There's no rush. Thanks for your great work.

**Comment by sondr3** [comment]
I just pushed a new version to Github, you can update to it with `npm install -g generator-jekyllized` and then run `yo jekyllized:update` in your project root folder so it correctly updates all your gulp tasks.
