### ISSUE TITLE
Support BrowserSync CSS injection

### ISSUE THREAD

**Issue by paulozoom** [sondr3/generator-jekyllized#143]
I noticed this existed before, with a `.pipe($.if(!argv.prod, browserSync.stream()))` call in the `styles` task, but a fresh generation of jekyllized fully reloads the page when the CSS changes, which makes the process of designing in the browser very slow.

Is there any chance this could come back?

**Comment by sondr3** [comment]
Slow? On my machine the difference is so small that before I can move my eyes to my second monitor it has fully refreshed. But maybe, I just couldn't get it to work at all last time with the structural changes to the temporary directories, feel free to take a stab at it too. I'll take a look when I get back home.

**Comment by paulozoom** [comment]
@sondr3 In my experience it was slower for sure, but more than that, a full refresh will close any modals, collapse any expanded menus, and clear any filled-out forms, things that direct injection of CSS would avoid.

**Comment by sondr3** [comment]
That's true, hadn't considered that. I'll look into it tonight! I just remember it not working properly last time.

**Comment by sondr3** [comment]
I've looked into this and the changes are either so trivial I'm completely overlooking them or I'm going to have to do some changes to how it generates the CSS and JS, I'll figure something out.

**Comment by paulozoom** [comment]
Thanks so much for taking a look!

On Wed, Jul 27, 2016 at 6:32 AM, Sondre Nilsen <notifications@github.com> wrote:
I've looked into this and the changes are either so trivial I'm completely overlooking them or I'm going to have to do some changes to how it generates the CSS and JS, I'll figure something out.

**Comment by sondr3** [comment]
Done! I've published a new version of the generator to NPM so you can install it again and run `yo jekyllized:update` to get the new configuration. You'll have to delete `styles.js`, `scripts.js` and `browsersync.js` because I had to merge them into `assets.js` 😃
