### ISSUE TITLE
Error Cannot GET /

### ISSUE THREAD

**Issue by alekcarvalho** [sondr3/generator-jekyllized#145]
When I run gulp command and the serve start, the browser show this error: cannot GET /

How I fix this?

Thx

**Comment by sondr3** [comment]
That normally happens when Jekyll hasn't installed properly, have you tried running `bundle install` to check if that makes it work? If not, can you paste the output of running `gulp`?

**Comment by alekcarvalho** [comment]
Hey @sondr3, 

I fixed the problem. Just needed to install the a Ruby DevKit.

Thx for help!

**Comment by YoungElPaso** [comment]
For me, the issue was I was using the default Ruby installed on my machine.  Used RVM to get another, re-installed bundler, re-installed bundle and worked.

**Comment by sondr3** [comment]
I'm guessing macOS? If that's the case you're not the first that has the problem, it has a problem with FFI that Jekyll requires. Let me know though, might have to add a disclaimer to the README about macOS.
