### ISSUE TITLE
Updated today and new project is failing in a few spots

### ISSUE THREAD

**Issue by Blumed** [sondr3/generator-jekyllized#156]
running: 
nvm - node 4.2.1
jekyll - 3.3.1
jekyllized - 3.3.6
OS - mac - Sierra

I want to point out I have 2 of your builds running perfectly fine on other projects, but today a fresh install is breaking in a few spots.

1. Yet another issue with node-sass. Seems like everyone has issues with node-sass. 
Gulp-sass needs to update from @2.1.1 to @3.13. Build won't enable the next layer of errors until I change this and run npm install yet again.

2. Now I get errors about jekyll-paginate, and jekyll-gist. Adding them to the _config.yml like
`gems: [jekyll-paginate, jekyll-gist]`

3. Now everything runs and my output stops at`[23:41:33] Finished 'jekyll:dev' after 1.1 s` and then it just sits. No errors. No warnings. I have been putting console logs in different sections and nothing seems to be outputting anything interesting.

<img width="519" alt="screen shot 2016-11-18 at 11 41 36 pm" src="https://cloud.githubusercontent.com/assets/2773888/20453385/be41be72-ade8-11e6-8046-254538d8e73f.png">
 
Any ideas? I'm at a loss.

P.s. I also want to thank you. I have learned a lot about jekyll and gulp from your code. I built a few jekyll/gulp builds myself and by doing so I learned to appreciate how you set up your build environment.

**Comment by Blumed** [comment]
Here is my repo that won't build. https://github.com/Blumed/deviceinfo

**Comment by sondr3** [comment]
Hey, I'll take a look as soon as I can. Might not be until Monday when I've finished my exam :)

**Comment by sondr3** [comment]
Sorry, I completely forgot to get back to you! I couldn't find any issues locally when I tested it two weeks ago but now that I've updated Node I can't even get it to run gulp due to some incompatibilities with the latest version of Node, so I'll have to look into it. 😅 Did you solve it yourself. I'm so sorry for not getting back to you in due time.

**Comment by Blumed** [comment]
Hey man,
Thanks for getting back to me. No worries 👍 
I have not solved it yet. You will be the first to know if I do.

**Comment by Blumed** [comment]
Just did a fresh install again and ran the following. I am on node 4.2.6, gulp 3.3.8 and updated gulp-sass and node-sass. Deleted the node_modules folder and ran npm install again. Everything downloaded perfectly on the first go this time. Yay! progress

-Next I get warning about jekyll-paginate. It was not in my gem file when I downloaded it. I added it and ran `bundle` plus added gems: [jekyll-paginate] to _config.yml

-Next error!
`Since v3.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Check http://jekyllrb.com/docs/upgrading/ for more info.`
In _config.yml I changed relative_permalinks to false.

-Next error!
`  Liquid Exception: Liquid syntax error (line 49): Unknown tag 'gist' in /Users/Master/Sites/jekyllized/src/_drafts/2014-03-01-example-content.md`

I added gems: [jekyll-paginate, jekyll-gist] to the _config.yml and jekyll-gist to the gemfile and ran bundle.

BOOOOOOM! it works :)

So there seems to be some items missing for me. node-sass, gulp-sass, jekyll-paginate, jekyll-gist. Did you not run into all of this?

**Comment by Blumed** [comment]
here is what my files looked like when I downloaded them.
gemfile:

source "http://rubygems.org"

gem 'jekyll'
gem 'redcarpet'
gem 'classifier-reborn'
gem 'fast-stemmer'
gem 'jekyll-paginate'
gem 'jekyll-gist'

_config.yml:

# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: 
description: 
tagline: 
url: localhost:4000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: 
  email: 
  bio: 
  twitter: 

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink: pretty
paginate: 10
paginate_path: 'page:num'
excerpt_separator: ''

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

**Comment by Blumed** [comment]
Do think this an issue with needing to purge the old version of your generator before I download your updated version? I updated your package using the yo update. The output of the two files look exactly like how they did in your previous versions.

**Comment by sondr3** [comment]
No idea, none of this looks correct to me and is not the intended output. I'll look into it tomorrow.

**Comment by Blumed** [comment]
Did a fresh install on my new work computer. Exact same issues.

**Comment by sondr3** [comment]
Your config file looks nothing like the one that's supposed to be created, are you sure you're not doing something weird? It's supposed to look like [this](https://github.com/sondr3/generator-jekyllized/blob/master/generators/jekyll/templates/config.yml), not whatever yours look like. You're actually overwriting the files when updating, right?

**Comment by Blumed** [comment]
On my work computer, I installed your generator for the first time. So.... ???
I am not 100% sure if they are overwriting. I assume when I update your package -g it is. I have run the update yo way and the npm update generator-jekyll -g both give me a broken install.

**Comment by sondr3** [comment]
When you run the generator again in the directory you want to update it'll ask you whether you want to overwrite the files, which you should do because it'll update it. Otherwise you end up with old settings that are incompatible with the latest version.

**Comment by Blumed** [comment]
I am spinning up a new folder each time. I am not updating in a pre existing folder.

**Comment by Blumed** [comment]
my work computer that I tried this morning didn't have yo or your generator on it when I installed it.

**Comment by Blumed** [comment]
Would you like to screenshare?

**Comment by sondr3** [comment]
You are actually not running the latest version, I think it might be with how your version of Node and NPM interprets versions, because the latest version should be `1.0.0-rc.7`, not `0.7.4` (which you are using, and it's _really_ old). If you want to update to the actual latest version you could run `npm install -g generator-jekyllized@1.0.0-rc.7` to install the latest version. Although you'll still have to update `gulp-sass` manually.

**Comment by Blumed** [comment]
interesting. Okay, switched to a 4.2.6 using nvm. Added the gulp-cli, yo, your generator. Everything installed perfectly. You have a .tmp/src directory in this installation?

**Comment by Blumed** [comment]
I can fix the pathing, but the first load is showing up "Cannot GET /"

**Comment by Blumed** [comment]
I didn't have to update gulp-sass by the way.

**Comment by sondr3** [comment]
Yep, you could also look at the top of the gulpfile and you should see what version of the generator was used to generate the setup. And the error with `Cannot GET /` usually means there's a problem with Jekyll, which is always fun. Try to do `bundle clean --force` and `bundle install` and see if that fixes the problem. The error with `gulp-sass` might only be with my version of Node then, nice to know.

**Comment by Blumed** [comment]
nah, that one is my bad. New computer. I didn't set up my gem installs.

**Comment by Blumed** [comment]
styles are not loading tho. I am figuring it out tho 👍

**Comment by Blumed** [comment]
Looks like they should by injected? reading the commented out sections?

**Comment by sondr3** [comment]
Yeah, when running `gulp` command it'll look for your assets and automatically inject them, or at least, it should do that.

**Comment by Blumed** [comment]
Dude, I'm solid. I really like what you're doing with gulp task breakouts. Babel is awesome.
Post mortem - I needed to use a specific revision like "npm install -g generator-jekyllized@1.0.0-rc.7" instead of "npm install -g generator-jekyllized".

**Comment by Blumed** [comment]
Thanks for all your help!

**Comment by sondr3** [comment]
No problem at all! Happy it worked out in the end. Just a bit strange that it didn't install the latest pre-release version automatically, it does so on my computer. But oh well 😃
