### ISSUE TITLE
`site.static_files` only finds root files

### ISSUE THREAD

**Issue by Koslun** [sondr3/generator-jekyllized#162]
Adding the following to `index.html` from a freshly generated project (using the `default` gulp task):

```html
  {% for file in site.static_files %}
  {{ file.path }}
  {% endfor %}
```

yields the output in the front page:

```bash
/crossdomain.xml
/humans.txt
/robots.txt
```

Investigating further I see that adding other sub-folders other than in `src/assets` correctly generates for instance a picture in `src/images/` named `bald_eagle.png`. Thus yielding this output:

```
/crossdomain.xml
/humans.txt
/images/bald_eagle.png
/robots.txt
```

Reproduced the above using Windows 10. Had the same issue on a slightly changed version of the project on another computer using Ubuntu 16.04 as well as on Windows 10.

On Windows 10 I further have the following global libs in-use:
```bash
Node.js@ 6.9.2
npm@ 3.10.9
yo@ 1.8.5
generator-jekyllized@1.0.0-rc.7 # used in both projects
gulp-cli@1.2.2
yarn:@ 0.24.6 # installed using yarn in both project

Ruby@ 2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]
Bundler@ 1.14.6
Sass@ 3.4.24
Jekyll@ 3.4.3
```

Chose to use `Babel`, `permalink `using `date `and `Rsync` as deployment for both generated project using version `1.0.0-rc.7` of the generator

### Conclusion
So though I am very new to Jekyll I am surmising that nothing in the `src/assets `folder is passed to Jekylls Liquid renderer. I don't know of any use for this other than file iteration using `site.static_files` but think it's a nifty and common enough feature that might be worth fixing.

**Comment by sondr3** [comment]
I'm not really sure why this is something that you'd ever use or need, and the way that Gulp processes files having to include the `src/assets` folder would just result in tons of extra copying whenever Gulp detects a change. This is not something that's going to change for this version, but might in the next version that I'm building.

**Comment by Koslun** [comment]
To avoid code duplication should we ever want to list a lot of images in a similar fashion. An example from a [stackoverflow post](https://stackoverflow.com/questions/17677094/jekyll-for-loop-over-all-images-in-a-folder):

My images are in a assets/images/slider directory.
```
{% for image in site.static_files %}
    {% if image.path contains 'images/slider' %}
        <img src="{{ site.baseurl }}{{ image.path }}" alt="image" />
    {% endif %}
{% endfor %}
```

It is further a feature in Jekyll that is described in the [docs](https://jekyllrb.com/docs/static-files/). So figure that there could be others who at least want to try it out.

You can however always type out a loop. So it is never necessarily *needed* to complete a task but arguably something some might want to do regardless, maybe just to try it out.

I understand your performance reasons for avoiding it and anyone who wants it just has to change the gulp config.

Might suggest a readme update to avoid this from happening again.

**Comment by sondr3** [comment]
That's fair enough, I'll look into maybe excluding the images folder in the assets directory on the next release. 😃
