### ISSUE TITLE
Regarding the gulp process

### ISSUE THREAD

**Issue by seshaljain** [sondr3/generator-jekyllized#173]
So I created a minima + gulp skeleton majorly based on the single-gulpfile branch with the latest dependencies. It works! 🎉

Now while going through the files, I had a few questions:
- Why a separate fonts tasks and not copy:fonts? It feels more semantic (I think)
- UglifyJS3 has removed the preserveComments option so I think it should reflect in assets.js as well
- Even _config.yml should be watched because we're only `jekyll build`ing the files
- `bundle exec jekyll ...` Is a better way to prevent dependency gems problems
- The babel-preset-es2015 package is deprecated and should be added as devDependency only if user selects Babel
Any ETA on v2? :+1:

**Comment by sondr3** [comment]
I don't know if you noticed but in the README it says that I'm looking for a co-maintainer. The generator is severely out of date and in need of touching up, but I don't really have the time for it. If you want to you can try to help out with it :)
