### ISSUE TITLE
fix spelling error in watch task

### ISSUE THREAD

**Issue by thiago-om** [sondr3/generator-jekyllized#67]
spelling error:

```gulp.watch(['serve/assets/stylesheets/*.css', 'serve/assest/javascript/*.js'], reload);```

should be:

assets
``gulp.watch(['serve/assets/stylesheets/*.css', 'serve/assets/javascript/*.js'], reload);```

- - - -

**Side note:** Also, at the moment, when editing JS gulp watch does not watch for changes in `/src` and therefore the only way to see the changes is to kill gulp and start again so jekyll copies the files over to `/serve`

EDIT: as a temporary fix I have made the following modification to the generated gulp file:

add ```'src/**/*.js'``` to rebuild list"
```gulp.watch(['src/**/*.md', 'src/**/*.html', 'src/**/*.xml', 'src/**/*.txt', 'src/**/*.js'], ['jekyll-rebuild']);```

**Comment by sondr3** [comment]
Hey, feel free to shoot a pull request too if you come across stuff like this too. I'll try to fix this over the weekend if I find time, your solution sounds fine. I really don't use JS myself so completely overlooked this, thank you!

**Comment by thiago-om** [comment]
No problem at all, I'll sort it out now :)
