### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by clawfire** [sondr3/generator-jekyllized#73]
My `npm` is installed by `brew` fyi.

When I run the install generator command I got this : 

```
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "generator-jekyllized"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /Users/thibault/.npm/ip-regex/1.0.3
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/Users/thibault/.npm/ip-regex/1.0.3'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/Users/thibault/.npm/ip-regex/1.0.3']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/thibault/.npm/ip-regex/1.0.3',
npm ERR!   parent: 'url-regex' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/thibault/npm-debug.log
```

**Comment by sondr3** [comment]
This isn't an issue with this generator but with NPM itself, the error code `EACCES` means that it doesn't get write access to your NPM directory. You can try `sudo chown -R $(whoami) ~/.npm` (or wherever the NPM directory is) or install Node as this article explains to get NPM properly setup: https://gist.github.com/DanHerbert/9520689. Hope it helps.

**Comment by clawfire** [comment]
But it works for all other generators I'd install just before and after. Weird

**Comment by sondr3** [comment]
It was probably one of the dependencies or something that got messed up, I can't really tell you either but I hope you managed to get it fixed! :smiley:
