### ISSUE TITLE
Errors on installation

### ISSUE THREAD

**Issue by CalebEverett** [sondr3/generator-jekyllized#76]
When I run 'npm install generator-jekyllized' I'm getting the following errors. I realized this is likely not actually an issue with jekylilzed, but any tips you might be able offer on how to fix my set up would be greatly appreciated. I'm not behind a proxy.

33868 verbose unlock done using C:\Users\caleb.everett\AppData\Roaming\npm-cache\_locks\inquirer-d712935131bf9a37.lock for d:\projects\nikoeverett\node_modules\generator-jekyllized\node_modules\yeoman-generator\node_modules\inquirer
33869 verbose stack Error: read ECONNRESET
33869 verbose stack     at exports._errnoException (util.js:746:11)
33869 verbose stack     at TCP.onread (net.js:550:26)
33870 verbose cwd d:\projects\nikoeverett
33871 error Windows_NT 6.3.9600
33872 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "generator-jekyllized"
33873 error node v0.12.0
33874 error npm  v2.5.1
33875 error code ECONNRESET
33876 error errno ECONNRESET
33877 error syscall read
33878 error network read ECONNRESET
33878 error network This is most likely not a problem with npm itself
33878 error network and is related to network connectivity.
33878 error network In most cases you are behind a proxy or have bad network settings.
33878 error network
33878 error network If you are behind a proxy, please make sure that the
33878 error network 'proxy' config is set properly.  See: 'npm help config'
33879 verbose exit [ 1, true ]

**Comment by sondr3** [comment]
I haven't really seen anything like this, it looks like NPM can't connect with it's repository online. Have you tried with node 0.10 instead of 0.12? I had a bunch of issues with 0.12 myself when I tried it.

**Comment by CalebEverett** [comment]
Made some progress. I installed npm in my project directory and got the generator installed and built with `yo jekyllized`. Now when I run `gulp` I'm getting the following.

```
[08:10:42] Using gulpfile d:\projects\nikoeverett\gulpfile.js
[08:10:42] Starting 'styles'...
[08:10:42] Starting 'jekyll:dev'...
[08:10:42] Starting 'watch'...
[08:10:42] Finished 'watch' after 36 ms
[08:10:42] 'jekyll:dev' errored after 57 ms
[08:10:42] Error in plugin 'gulp-shell'
Message:
    Command failed: C:\Windows\system32\cmd.exe /s /c "jekyll build"
'jekyll' is not recognized as an internal or external command,
operable program or batch file.

Details:
    killed: false
    code: 1
    signal: null
    cmd: C:\Windows\system32\cmd.exe /s /c "jekyll build"
    stdout: 
    stderr: 'jekyll' is not recognized as an internal or external command,
operable program or batch file.

[08:10:43] 'styles' all files 19.41 kB
[08:10:43] Finished 'styles' after 553 ms
```

**Comment by CalebEverett** [comment]
I didn't have jekyll installed.

**Comment by sondr3** [comment]
Haha, that could explain it :smile:
