### ISSUE TITLE
Documentation: Change the branch that the gulp deploy pushes to

### ISSUE THREAD

**Issue by mashcode** [sondr3/generator-jekyllized#81]
Can you explain this is a little more detail?

Should one use baseurl?

**Comment by sondr3** [comment]
Did you take a look at [this](http://jekyllrb.com/docs/github-pages/) link? It's from Jekylls documentation on hosting on Github Pages. If you have any more questions just ask.

**Comment by mashcode** [comment]
Hey Sondr3, sorry about the delay getting back.  I was able to cobble together a fix for project pages using baseurl, pointing gulp deploy at gh-pages with a gulp task that adds a CNAME record.

The speed of your generator is 👍👍👍just needs a doctor for gulp serve 🙏🏻

**Comment by sondr3** [comment]
No worries, glad to hear you were able to fix it. Just ask away if you need more help :smile: And thanks for the kind words.
