### ISSUE TITLE
Nothing but images/ in site/assets/

### ISSUE THREAD

**Issue by tylersloan** [sondr3/generator-jekyllized#82]
I am using Jekyllized for a project, and made the appropriate changes to enbable `$ gulp deploy` but the build isn't including the css or js directories inside images–only the images directory. 

Anyone else had a similar situation? I may well be over-looking something but I'm just not seeing what the problem is.

**Comment by tylersloan** [comment]
I see `.pipe(gulp.dest("site/assets/images"))` inside the images task.

Does something like that need to be inside the styles? I don't even see anything about what to do with .js files other than concat and run js lint.

**Comment by sondr3** [comment]
Really? That's really strange, I've never seen anything like that nor should that happen because all the tasks does have `gulp.dest` pipes in them. I'm curious, from looking at your gulpfile, what command do you run when you build your site/try to publish it? Because the `build` task is missing a bunch of commands that it normally should have.

**Comment by sondr3** [comment]
Nevermind, I've been working on the beta/yeoman-next branch for so long I hardly recognize the gulpfile in the master branch, haha. Hmm, not really sure what the problem could be then, I'll clone your project and play around.

**Comment by tylersloan** [comment]
Ha. Alright, thanks for poking around. 

For what it's worth, I messed up my gh-pages branch and when I started over, I think I ran `gulp build` and `gulp publish` before `gulp deploy`.

**Comment by sondr3** [comment]
Alright, did it work fine before? Have you tried deleting the `node_modules` folder and reinstalling the NPM packages?

**Comment by sondr3** [comment]
Strange, I just cloned your project, installed the NPM packages and the gems and it works just fine, the `assets` folder has both images, javascript and CSS in it, the only problem was the `baseurl` setting which caused some problems... Have you figured it out on your end? What version of Node/NPM are you running etc?

**Comment by tylersloan** [comment]
I have reinstalled NPM modules. 

My npm --v is 2.5.1 & node --version is v0.12.0

**Comment by sondr3** [comment]
Huh, that's really strange. What version of Ruby are you running then? Because everything works fine here. I'm using `Node v0.12.4`, `npm 2.7.3` and `ruby 2.2.0`. I'm at a bit of a loss as to what is happening since it works fine when just cloning your project for me.

**Comment by tylersloan** [comment]
I changed the baseurl since it's for a project. Are you saying that was a mistake?

I see that the files are being generated, yes. But they aren't making it to my gh-pages branch during `gulp deploy`.

**Comment by sondr3** [comment]
Oh, is that the problem? I thought it was that it wasn't generating the files needed. My bad. I'll take another look.

**Comment by sondr3** [comment]
Okay, so I ran the thing again and created a repo for myself here: https://github.com/sondr3/tyler.works. Everything again works as expected for me, the only thing I had to do was update the `gulp-gh-pages` package for it to upload. After you've run `gulp publish` (you don't need to run `gulp build`, it does that automatically first) is the `assets` directory still missing the CSS and JS?

**Comment by sondr3** [comment]
Weird, now your problem actually appeared after uploading it a few times. Huh. This is weird.

**Comment by tylersloan** [comment]
Yeah no luck over here, either after updating gulp-gh-pages.

**Comment by sondr3** [comment]
If you're willing I'd give the beta branch a try, but it does require you to install and use the Gulp 4.0 and Jekyll 3.0 which both are currently in betas, but I haven't had any of these problems with it. I'll try some more because I'm fairly sure the problem is with the `html` task, just not sure why.

**Comment by sondr3** [comment]
Although you have to change the `gulp` package info in the `package.json` file to `"gulp": "git://github.com/gulpjs/gulp#4.0"`

**Comment by tylersloan** [comment]
I'll try beta out tonight. Let me know if you find anything. Thanks for helping.

**Comment by sondr3** [comment]
No worries, I just pushed a minor update to the beta branch so it'll work out of the box with `gulp` and whatnot, everything should work there. Let me know how it works out.
