### ISSUE TITLE
Most of files have execute permissions

### ISSUE THREAD

**Issue by solker** [sondr3/generator-jekyllized#84]
Why we need it? It's looking dangerous. 

![selection_090](https://cloud.githubusercontent.com/assets/10127295/8035669/1d6d5904-0dfb-11e5-8701-4f6d3be29cf5.png)

To fix it I executed next command in the main root repository:
`find . -type f -executable -exec chmod -x {} \;`

But i can't make PR because of permissions.

Thanks.

**Comment by sondr3** [comment]
You can't make a PR because of the permissions on the file you mean? And thanks for letting me know, wasn't aware of that, I'll look into it :smile:

**Comment by solker** [comment]
No i can't make PR because i can't upload my branch to this repository.

**Comment by sondr3** [comment]
That's not how PR works, you fork this repo, create a new branch in your own clone and push that to Github and then open a PR. https://help.github.com/articles/using-pull-requests/ :)

**Comment by sondr3** [comment]
I've now pushed an update to remove the execute permissions I could find in the files.
