### ISSUE TITLE
Something wrong on my project github page deployment

### ISSUE THREAD

**Issue by t0t** [sondr3/generator-jekyllized#85]
Hello,
After following this:
https://www.npmjs.com/package/generator-jekyllized#github-pages
js and css continue without adding ``/jekyllized/...`` to the paths under ``site``folder.

This is what i got:
link rel="stylesheet" href="/assets/stylesheets/style.min.css

This is what I wish:
link rel="stylesheet" href="/jekyllized/assets/stylesheets/style.min.css"

What's wrong on my gulp file? Please any help would be apreciated.

This is the repo: https://github.com/t0t/jekyllized/tree/master

thanks a lot!
![captura de pantalla 2015-06-08 a las 13 22 15](https://cloud.githubusercontent.com/assets/6004806/8041697/674a5044-0e1a-11e5-9460-30857de170c4.png)

**Comment by sondr3** [comment]
From looking at your config files you should remove the `url: t0t.github.io/jekyllized` and just have it be `url: t0t.github.io` and keep the baseurl in the `_config.yml` file. Try that first and if that doesn't work you probably need to add a `baseurl: /jekyllized` to your `_config.build.yml` file so it builds it properly and change the URL to just the domain. It'd be something like:

```
# Overrides the default URL, needed for your atom feed and sitemap
url: t0t.github.io
baseurl: /jekyllized
````

**Comment by sondr3** [comment]
Also, have you added the `{{ baseurl }}` setting to your templates? Otherwise it'll render it wrong, if you looked at the [Jekyll guide](http://jekyllrb.com/docs/github-pages/) that I link in the README you have to do that too otherwise it just omits the `baseurl`.

**Comment by t0t** [comment]
thanks sondr3 for the reply,
I tried to follow step by step your recomendations and all fine on local dev, nav work also well on deploy... 

**the only thing is css path not loading when in deploy** http://t0t.github.io/jekyllized/ 

It is all a bit confusing and flustrating for me. This is my face now :frog: 

Why do you think ``link rel="stylesheet" href="{{ site.baseurl }}/assets/stylesheets/style.css"``is not loading well on deploy?

thanks.

![captura de pantalla 2015-06-09 a las 2 51 29](https://cloud.githubusercontent.com/assets/6004806/8048477/0c82f098-0e52-11e5-9d1c-33d018d9678d.png)

**Comment by sondr3** [comment]
Not too sure, your Jekyll code looks fine, but I'm thinking it's the Gulpfile that's the problem, right now the master branch is running on a pretty old version of what I'm currently using. If you want to you could install Gulp 4 and try from the Gulpfile in the beta branch, but it's a bit of a hassle installing Gulp 4. Otherwise I'll take a look tomorrow because it's pretty late here right now.

**Comment by t0t** [comment]
hey! 
I'll continue with actual gulp version until new one is released or maybe I'll try to do all these good things like concat, minify, livereload... with npm packages directly.
If you can I really would appreciate but if you are busy I understand.

thanks, you are doing an interesting work with jekyllized! :sun_with_face:

**Comment by t0t** [comment]
I've changed my mind, jekyllized is awesome. I'll try to install gulp 4 now!!
http://demisx.github.io/gulp4/2015/01/15/install-gulp4.html
:grin:

**Comment by sondr3** [comment]
Awesome, when you do I recommend you actually install the beta branch from Jekyllized instead of the master, it'll be mostly the same but you'll run the newest versions of both Jekyll and Gulp. You need to uninstall jekyllized first though: `npm uninstall generator-jekyllized` and then install the beta branch: `npm install -g sondr3/generator-jekyllized.git#beta`. Should work :)

**Comment by t0t** [comment]
I have not uninstall already installed, can be a problem?

t0t-2:sites o0$ sudo npm uninstall generator-jekyllized
Password:
npm WARN uninstall not installed in /Users/o0/Dropbox/TRABAJO/sites/node_modules: "generator-jekyllized"

**Comment by sondr3** [comment]
Oh, right, sorry, you need to uninstall it globally: `npm uninstall -g generator-jekyllized`

**Comment by t0t** [comment]
hey! 
I'm close...
installed gulp 4 and jekyllized-beta
some warnings during the process but I can see on local ``gulp``
The error shows on ``gulp deploy``:
``jekyllized4 o0$ gulp deploy
[02:08:33] Using gulpfile ~/Dropbox/TRABAJO/sites/jekyllized4/gulpfile.js
[02:08:33] Starting 'deploy'...
[02:08:33] 'deploy' errored after 165 ms
[02:08:33] TypeError: Cannot read property 'reject' of undefined
    at Function.prepareRepo (/Users/o0/Dropbox/TRABAJO/sites/jekyllized4/node_modules/gulp-gh-pages/lib/git.js:80:11)
    at DestroyableTransform.task [as _flush] (/Users/o0/Dropbox/TRABAJO/sites/jekyllized4/node_modules/gulp-gh-pages/index.js:52:14)
    at DestroyableTransform.<anonymous> (/Users/o0/Dropbox/TRABAJO/sites/jekyllized4/node_modules/gulp-gh-pages/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at finishMaybe (/Users/o0/Dropbox/TRABAJO/sites/jekyllized4/node_modules/gulp-gh-pages/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (/Users/o0/Dropbox/TRABAJO/sites/jekyllized4/node_modules/gulp-gh-pages/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (/Users/o0/Dropbox/TRABAJO/sites/jekyllized4/node_modules/gulp-gh-pages/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
    at DestroyableTransform.onend (/Users/o0/Dropbox/TRABAJO/sites/jekyllized4/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16) ``

Any idea? Thanks for help!

**Comment by sondr3** [comment]
Try installing the most recent version and see if that helps: `npm install --save-dev gulp-gh-pages@0.5.2`. Otherwise you can push it to Github and I'll take a look at that too :)

**Comment by t0t** [comment]
hey @sondr3!
things going better!
the repo: https://github.com/t0t/jekyllized4/
deploy worked fine but bassically y get the same problem with routing paths: http://t0t.github.io/jekyllized4/

Could I fix the same way that i did last time or is different in beta version?

thanks a lot, ;)

**Comment by sondr3** [comment]
Yeah, because it hasn't been configured with a `baseurl` yet. Add the `baseurl: /jekyllized` to `_config.yml` and then go to your `src/_includes/head.html` and add `{{ site.baseurl }}` to this:

```html
  <!-- build:css /assets/stylesheets/style.min.css -->
  <link rel="stylesheet" href="/assets/stylesheets/style.css">
  <!-- endbuild -->
```

like this:

```html
  <!-- build:css {{ site.baseurl }}/assets/stylesheets/style.min.css -->
  <link rel="stylesheet" href="{{ site.baseurl }}/assets/stylesheets/style.css">
  <!-- endbuild -->
```

And then in `src/_layouts/default.html``` change


```html
  <!-- build:js /assets/javascript/index.min.js -->
  <script src="/assets/javascript/index.js"></script>
  <!-- endbuild -->
```

to

```html
  <!-- build:js {{ site.baseurl }}/assets/javascript/index.min.js -->
  <script src="{{ site.baseurl }}/assets/javascript/index.js"></script>
  <!-- endbuild -->
```

That should work, I haven't been able to test it, but if it doesn't work this is basically what needs to be done with the assets. I'll take a look later when I wake up if things still aren't working :)

**Comment by t0t** [comment]
ups, not yet...
I'll try adding baseurl to _config.build.yml too.

**Comment by t0t** [comment]
Still not linking fine. :sweat:

It have to do anything with my ruby install. I get some console warnings:
``Ignoring yajl-ruby-1.1.0 because its extensions are not built.  Try: gem pristine yajl-ruby-1.1.0
Ignoring gosu-0.7.50 because its extensions are not built.  Try: gem pristine gosu-0.7.50
Ignoring redcarpet-2.3.0 because its extensions are not built.  Try: gem pristine redcarpet-2.3.0
Ignoring yajl-ruby-1.1.0 because its extensions are not built.  Try: gem pristine yajl-ruby-1.1.0
WARN: Unresolved specs during Gem::Specification.reset:
      pygments.rb (~> 0.6.0)
      redcarpet (~> 3.1)
      jekyll-watch (~> 1.1)
      classifier-reborn (~> 2.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/version.rb:3: warning: already initialized constant JSON::VERSION
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/version.rb:3: warning: previous definition of VERSION was here
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/version.rb:4: warning: already initialized constant JSON::VERSION_ARRAY
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/version.rb:5: warning: already initialized constant JSON::VERSION_MAJOR
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/version.rb:6: warning: already initialized constant JSON::VERSION_MINOR
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/version.rb:7: warning: already initialized constant JSON::VERSION_BUILD
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:99: warning: already initialized constant JSON::NaN
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/common.rb:99: warning: previous definition of NaN was here
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:101: warning: already initialized constant JSON::Infinity
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/common.rb:101: warning: previous definition of Infinity was here
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:103: warning: already initialized constant JSON::MinusInfinity
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/common.rb:103: warning: previous definition of MinusInfinity was here
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/json/common.rb:128: warning: already initialized constant JSON::UnparserError
/Library/Ruby/Gems/2.0.0/gems/json-1.8.1/lib/json/common.rb:128: warning: previous definition of UnparserError was here``

**Comment by sondr3** [comment]
And then the problems are with Ruby, haha, nice. Hmm, have you tried uninstalling your gems and reinstalling them? Also, what version of Ruby are you running?

**Comment by sondr3** [comment]
I'm going to close this issue as I haven't heard anything from you since our last conversation, feel free to open it if you want to :smiley:

**Comment by emilianos** [comment]
Ok, so I had a similar problem with baseurl, and found out that gulp was injecting (gulp-inject), styles and js so there was no point in changing the href in the templates (they were getting overridden every time).

I finally was able to accomplish it by editing my gulpfile as follows:

from:
```
gulp.task('inject:head', () =>
  gulp.src('src/_includes/head.html')
    .pipe($.inject(gulp.src('.tmp/assets/stylesheets/*.css',
                            {read: false}), {ignorePath: '.tmp'}
    .pipe(gulp.dest('src/_includes'))
);
```

to:
```
gulp.task('inject:head', () =>
  gulp.src('src/_includes/head.html')
    .pipe($.inject(gulp.src('.tmp/assets/stylesheets/*.css',
                            {read: false}), {addPrefix: '{{ site.baseurl }}', ignorePath: '.tmp', addRootSlash:false}))
    .pipe(gulp.dest('src/_includes'))
);
```

Just noting this down for future reference.

**Comment by sergimiral** [comment]
As commented above, gulp-inject changes some paths and the workaround proposed works. Furthermore, I needed to do some more changes but I think I got it working - leaving it here just in case it helps someone & for future reference. 

**1** – Added `baseurl: /project-name` to _config.build.yml

**2** – In gulpfile.babel.js changed the inject:header section from:
```
gulp.task('inject:head', () =>
  gulp.src('src/_includes/head.html')
    .pipe($.inject(gulp.src('.tmp/assets/stylesheets/*.css',
                            {read: false}), {ignorePath: '.tmp'}
    .pipe(gulp.dest('src/_includes'))
);
```
to:
```
gulp.task('inject:head', () =>
  gulp.src('src/_includes/head.html')
    .pipe($.inject(gulp.src('.tmp/assets/stylesheets/*.css',
                          {read: false}), {addPrefix: '{{ site.baseurl }}', ignorePath: '.tmp', addRootSlash:false}))
    .pipe(gulp.dest('src/_includes'))
);
```

**3** – In gulpfile.babel.js changed the inject:footer section from:
```
gulp.task('inject:footer', () =>
  gulp.src('src/_layouts/default.html')
    .pipe($.inject(gulp.src('.tmp/assets/javascript/*.js',
                          {read: false}), {ignorePath: '.tmp'}))
    .pipe(gulp.dest('src/_layouts'))
);
```
to:
```
gulp.task('inject:footer', () =>
  gulp.src('src/_layouts/default.html')
    .pipe($.inject(gulp.src('.tmp/assets/javascript/*.js',
                          {read: false}), {addPrefix: '{{ site.baseurl }}', ignorePath: '.tmp', addRootSlash:false}))
    .pipe(gulp.dest('src/_layouts'))
);
```

**4** – In default.html changed this:
```
<script src="/assets/javascript/index.min.js"></script>
```
to:
```
<script src="{{ site.baseurl }}/assets/javascript/index.min.js"></script>
```

**5** – In header.html changed this:
```
<link rel="stylesheet" href="/assets/stylesheets/style.min.css">
```
to:
```
<link rel="stylesheet" href="{{ site.baseurl }}/assets/stylesheets/style.min.css">
```

**6** – Now everything works locally and before deploying to gh-pages one should run `gulp build --prod`, so the *baseurl* variable added in the _config_build.yml file is taken in consideration – then `gulp deploy`
