### ISSUE TITLE
Image not being revisioned - Beta Branch

### ISSUE THREAD

**Issue by Rekenna** [sondr3/generator-jekyllized#87]
Hey there, I'm using the beta build after reading some similar issues where you recommended people to update. 

I'm using npm 0.12.2, gulp 4, jekyll 3. I was having issues with the jekyll plugins jekyll-archived & jekyll-sitemaps so I commented them out and I was able to build the site. After some messing around I was able to get the js/css to build and publish correctly. The images don't seem to do anything.

When I run gulp build 

Starting 'images'...
[12:03:51] 'fonts' all files 0 B
[12:03:51] Finished 'fonts' after 1.53 s
[12:03:53] 'styles' all files 120.3 kB
[12:03:53] Finished 'styles' after 3.7 s
[12:03:53] 'javascript' all files 540.67 kB
[12:03:53] Finished 'javascript' after 4.13 s
[12:03:54] 'images' all files 10.14 MB

however, they don't appear in .tmp

And when I run optimize, it doesn't detect any images to copy over from .tmp so they're not published. It's clearly detecting that they exist but doing nothing with them. 

Any ideas?

Thanks a bunch

**Comment by sondr3** [comment]
Sorry for the slow reply, been on vacation. I'm not 100% sure what the issue could be, have you tried removing the `$.cache` part of it? That could be the issue that it thinks the images is in the cache. Otherwise I'll have a look and see what I can figure out.

**Comment by Rekenna** [comment]
I haven't tried your suggestion yet, I won't be able to until I get home from work later most likely. My code is in the gh-pages of my main branch. rekenna.github.io in case you want to look at it. I was having a few errors but I've disabled some features to get most of it working. Thanks for getting back to me, I'll check back later when I've tried your suggestion.

**Comment by sondr3** [comment]
Tried removing that part? If you want to I can clone it locally and play around with it :)

**Comment by Rekenna** [comment]
I was able to try it earlier and as it turns out removing cache fixed the problem partially. Now the images are put into the .tmp folder when the site is built/served. However when running optimize the images are not copied over to dist.

**Comment by sondr3** [comment]
Yeah, the various caching plugins for Gulp has mostly been a pain to work with, I'll probably remove them. Can you try changing this:

```js
function copy() {
  var images = gulp.src(config.images.dest)
    .pipe(gulp.dest(config.images.build))
    .pipe($.size({title: 'copied images'}));
```

into

```js
function copy() {
  var images = gulp.src('.tmp/assets/image/**/*')
    .pipe(gulp.dest(config.images.build))
    .pipe($.size({title: 'copied images'}));
```

and see if it works?

**Comment by Rekenna** [comment]
There we go, that totally worked. I checked the config several times and I was wondering if it just wasn't picking up the path. The only other issue I was having is with the jekyll sitemap & archives plugin. I ended up commenting them out from both my gemfile and config.yml. 

I get the error

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jekyll-archives (LoadError)

Any insight? You've been very helpful so far, I really love the work you've put into this project. I have a feeling it might be a jekyll install issue.

**Comment by sondr3** [comment]
Yeah, basically I forgot the `**/*` in there, otherwise it skips all the files inside it. Small stuff like that that'll come back and bite you, haha. If you want to have it in your config file you can just add a separate entry for it:

```js
    "tmp": ".tmp/assets/images/**/*",
```

and use that. As for the Jekyll error, yeah, it's probably because you have it in your `_config.yml` file as well. Jekyll requires you to both list the gems in the `Gemfile` and `_config.yml` file. Look for the lines that say

```yml
gems:
    - jekyll-archives
    - jekyll-sitemap
```

And remove the offending gems.

**Comment by sondr3** [comment]
Scratch the last part about the gems, it's because you haven't removed the config settings for it underneath where the gems are listed in the `_config.yml`. Comment out all the lines from

```yml
jekyll-archives:
```

and down and it should be fine.

**Comment by Rekenna** [comment]
Even removing the config settings below I still have the same error

**Comment by sondr3** [comment]
Try removing the `Gemfile.lock` and running `bundle` again.

**Comment by Rekenna** [comment]
Nope :(

**Comment by sondr3** [comment]
Huh, strange. I'll clone and take a look.

**Comment by Rekenna** [comment]
I just committed to the gh-pages branch of my repo. If you want to take a look you're free to.

**Comment by sondr3** [comment]
Yeah, I've figured it out, just let me write it down real quick.

**Comment by sondr3** [comment]
Actually, I'll just fork and fix :smile:

**Comment by Rekenna** [comment]
That works for me :)

**Comment by sondr3** [comment]
Okay, it'll take a bit of time, you have some errors in your Liquid templates that needs to be fixed as well, haha.

**Comment by Rekenna** [comment]
That's not terribly surprising, I using your generator + jekyll as a learning experience. I really do appreciate the help.
