### ISSUE TITLE
Add Angular support

### ISSUE THREAD

**Issue by RuRios** [sondr3/generator-jekyllized#89]
It would be great if you could add AngularJS support. Perhaps provide an install time option to add it...?

**Comment by sondr3** [comment]
I have never used AngularJS before nor do I have any plans of using it in the future either nor do I really think it fits within the scope of this generator, which is really only a Gulp wrapper around Jekyll with some minor bits and pieces added, nothing major. Unless you'd be able to cook something up so I can take a look at it, I simply wouldn't be able to implement it out of unfamiliarity. Not really even sure what you'd use AngularJS for to be honest :smiley:
