### ISSUE TITLE
Rev images not being created

### ISSUE THREAD

**Issue by simply-simpy** [sondr3/generator-jekyllized#91]
Any thoughts on why my images are not being rev'ed?
For example: {background:url(../images/bg.dc42714e.jpg) } is generated in my CSS,  but there is not a corresponding image in my images directory.

**Comment by sondr3** [comment]
Yeah, it's some kind of strange interaction with the file-revving plugin that does that, I haven't really been able to figure out why it does those kinds of things, but I'm working on some stuff that I'll push to the beta branch when I figure something out.

**Comment by simply-simpy** [comment]
Thanks — for now I committed out line 92 [ .pipe($.revAll({ ignore: [".eot", ".svg", ".ttf", ".woff"] })) ] on my gulp.js file. Seems to be a good work around.

**Comment by sondr3** [comment]
Yeah, unless you absolutely need to rev your assets it can be ignored really, I'll let you know when I figure something out :)

**Comment by sondr3** [comment]
Just wanted to chime in, I've fixed this in the beta branch and moved away from the `gulp-rev-all` plugin and back to `gulp-rev`
