### ISSUE TITLE
Files not being minified when using 'gulp-deploy'

### ISSUE THREAD

**Issue by antonioOrtiz** [sondr3/generator-jekyllized#93]
I just noticed my files (JS, CSS, HTML) are not being minified. https://github.com/antonioOrtiz/antonioortiz.github.io
Is there something I am missing?

Thank you!

**Comment by sondr3** [comment]
It's a bit hard to tell, but from looking at your directory structure I'm not sure if Gulp actually knows where you assets live. Do you have a `serve` directory with all the files in it? Posts/CSS/JS etc?

**Comment by antonioOrtiz** [comment]
I do; The `serve` directory is generated, when I run the default `gulp` task, when I run `gulp-build` etc.

**Comment by sondr3** [comment]
Can you verify whether the assets are in there as well? There should be a `assets` directory containing all your assets there.

**Comment by antonioOrtiz** [comment]
There in there, but it looks more like a copy of the `src` folder...

**Comment by sondr3** [comment]
Which is what it should be like, just wanted to make sure it was there. Strange though, if you run the `gulp html` command, does it create a `site` directory with the assets inside?

**Comment by antonioOrtiz** [comment]
O.k. Seems like I figured something out. It appears a while back when I was testing everything, I had to change the original `return gulp.src('./site/**/*')` path for the `gulp-deploy` to pick-up the `serve` folder. Reason being, some of the the cache busting names to the new images were not being added to the files in the image folder.  Sorry for the runaround. But do you know why the task wouldn't be adding the new cache busted names?

**Comment by sondr3** [comment]
Oh, yeah, that's an issue that has happened before. You've changed the search for only HTML files, so all the tasks that look for CSS/JS and such won't do anything. What I'd do is just make it so it doesn't cache bust the images (and any other files that give you trouble): 

```js
.pipe($.revAll({ ignore: ['.eot', '.svg', '.ttf', '.woff',
                          '.jpg', '.png', '.gif'] }))
```

In all honesty I find cache busting to be incredibly painful to work with since there are so many weird edge cases and stuff, if you don't really need it I'd just comment out the line with `$.revAll` and change the `return gulp.src(' ')` back to how it was.

**Comment by sondr3** [comment]
Regarding not cache busting images, I have absolutely no idea why it doesn't do that. You're not the first to have that issue either, and I haven't figured out why it doesn't properly do those but does other things like fonts fine.

**Comment by antonioOrtiz** [comment]
Thanks so much. I added the `.jpg', '.png', '.gif` to the `.pipe($.revAll({ ignore: [ ......] }))` part of the `html` task. So the `css` and `js` minification and concatination is not affected?

**Comment by antonioOrtiz** [comment]
And image compression, not affected?

**Comment by sondr3** [comment]
No, adding file types to the `ignore` array just means that they aren't renamed and cache busted, everything works as normal it's just the names of those types of files that aren't touched. Just remember to change the `gulp return` line too :smile:

**Comment by antonioOrtiz** [comment]
Do you mean change `return gulp.src('serve/**/*.html')` to `  return gulp.src('site/**/*.html')`

This task?

    gulp.task('html', ['styles'], function () {
  var assets = $.useref.assets({searchPath: 'serve'});

  return gulp.src('serve/**/*.html')
    .pipe(assets)
    // Concatenate JavaScript files and preserve important comments
    .pipe($.if('*.js', $.uglify({preserveComments: 'some'})))

    // Minify CSS
    .pipe($.if('*.css', $.minifyCss()))

    // Start cache busting the files
    .pipe($.revAll({ ignore: ['.eot', '.svg', '.ttf', '.woff', '.jpg', '.png', '.gif'] }))
    .pipe(assets.restore())
    // Conctenate your files based on what you specified in _layout/header.html
    .pipe($.useref())
    // Replace the asset names with their cache busted names
    .pipe($.revReplace())
    // Minify HTML
    .pipe($.if('*.html', $.htmlmin({
      removeComments: true,
      removeCommentsFromCDATA: true,
      removeCDATASectionsFromCDATA: true,
      collapseWhitespace: true,
      collapseBooleanAttributes: true,
      removeAttributeQuotes: true,
      removeRedundantAttributes: true
    })))

    // Send the output to the correct folder
    .pipe(gulp.dest('site'))
    .pipe($.size({title: 'optimizations'}));
  });

**Comment by sondr3** [comment]
Ah, no, I misread. No, it should work fine now. What happens when you run the `gulp publish` command? Are the assets minified and such?

**Comment by sondr3** [comment]
I'm going to close this issue as I haven't heard anything from you since our last conversation, feel free to open it if you want to :smiley:
