### ISSUE TITLE
Js files

### ISSUE THREAD

**Issue by Budolfsen** [sondr3/generator-jekyllized#94]
Hi

I have a quick question which I hope you can answer.

I haven't change any structure from the original and haven't change anything in the gulpfils except removing the revall-line.

When I run gulp - it copies my files from src to serve, just as it should - and it is working great - but when I run gulp publish it only minifies the original js-files(javascript.js and somejavascript.js - not the other files in the js-folder)

What am I doing wrong - hope you can help....

**Comment by sondr3** [comment]
Hey, sorry to hear about the issues. I guess you are running the version from NPM? If you could push your project to Github I'd love to take a look and figure it out, otherwise I'm a bit lost at what could possibly be the error.

**Comment by Budolfsen** [comment]
I am running jekyllized through Yeomans generator....

Here is a link to the project https://github.com/Budolfsen/gadekoekkenet

**Comment by sondr3** [comment]
Yeah, when you look in your `footer.html` file in the `_includes` folder you'll see this code:

```js
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- build:js /assets/javascript/all.min.js -->
    <script src="/assets/javascript/javascript.js"></script>
    <script src="/assets/javascript/somejavascript.js"></script>
    <!-- endbuild -->
    <!-- ++++++++++++++++ SCRIPTS simpleCart ++++++++++++++++++ -->
    <script src="{{ site.baseurl }}/assets/javascript/simpleCart.min.js"></script>
```

You can see the `<!-- build:js ... -->` and `<!-- endbuild -->`, you need to put your JS files inside those two brackets or create another bracket, because otherwise the generator doesn't know that those files are to be optimised, it doesn't look for them outside those blocks.

**Comment by sondr3** [comment]
Also, there's no need to use `{{ site.baseurl }}` for this, the assets will work fine unless you publish to a subdomain. Just do it like the other JS files in the above code :smiley:

**Comment by Budolfsen** [comment]
I have removed the site.baseurl - I figured out it wasn't nescessary - but I get an strange error when I run gulp publish


events.js:85
      throw er; // Unhandled 'error' event
            ^
Error
    at new JS_Parse_Error (/Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:679:41)
    at token_error (/Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:683:9)
    at expect_token (/Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:696:9)
    at expect (/Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:699:36)
    at /Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1225:44
    at /Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:722:24
    at expr_atom (/Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1182:35)
    at maybe_unary (/Users/kentbudolfsen/Desktop/gadekoekkenet/node_modules/gulp-uglify/node_modules/uglify-js/lib/parse.js:1358:19)

I have updated everything - but still nothing works.... hope you have seen this error before....

**Comment by sondr3** [comment]
I haven't seen it but I suspect it has to do with jQuery, you really shouldn't minimize it yourself. Besides, you actually shouldn't include any JS that's already minified in the Useref block either because I think that messes with it. You should try to have one for the files that aren't minified and one for those that are minified. I'd change it to be:

```js
    <script src="/assets/components/jquery/dist/jquery.min.js"></script>
    <!-- build:js /assets/javascript/all.min.js -->
    <script src="/assets/javascript/javascript.js"></script>
    <script src="/assets/javascript/somejavascript.js"></script>
    <!-- endbuild -->
    <!-- build:js /assets/javascript/vendor.min.js -->
    <!-- ++++++++++++++++ SCRIPTS simpleCart ++++++++++++++++++ -->
    <script src="/assets/components/readmore/readmore.min.js"></script>
    <script src="/assets/javascript/simpleCart.min.js"></script>
    <!-- endbuild -->
```

Or something like that, could you try that and see how it works?

**Comment by sondr3** [comment]
Also, it might just be the `<!-- ++++++++++++++++ SCRIPTS simpleCart ++++++++++++++++++ -->` inside the Useref block that makes it break, try to remove it and move it outside the build blocks and see if that works.

**Comment by Budolfsen** [comment]
Got it to work - updated my entire npm, node, yeoman, jekyllized and so on - reinstalled and copied everything back into place..... then it worked.

**Comment by sondr3** [comment]
Great to hear, happy it started working :)
