### ISSUE TITLE
Warning after running gulp

### ISSUE THREAD

**Issue by mahlu** [sondr3/generator-jekyllized#98]
How can I get rid of this warning?       

Warning: The <noscript> tag for your gist 5555251 could not
                be generated. This will affect users who do not have
                JavaScript available or enabled in their browsers.

Warning: The <noscript> tag for your gist 5555251 could not
                be generated. This will affect users who do not have
                JavaScript available or enabled in their browsers.

**Comment by sondr3** [comment]
That looks like a issue with the jekyll-gist extension, not really sure what could be the problem though however. You should take a look at it or just outright disable it in the `_config.yml` file.

**Comment by mahlu** [comment]
Ok I'll do that, and thank you for this amazing generator!

**Comment by sondr3** [comment]
No problem, and thanks! :)
